version: 2
jobs:
  build:
    working_directory: ~/ECINGInious
    docker:
      - image: circleci/python:3.5
      - image: selenium/standalone-firefox:3.1.0
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3.5 install --upgrade pip
      - run:
          command: |
           PATH=/home/circleci/ECINGInious/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - run:
          command: |
           sudo apt-get install python-tidylib
      - run:
          command: |
            . venv/bin/activate
            pip3.5 install --upgrade --no-cache-dir '.[test]'
      - run:
          command: |
            . venv/bin/activate
            python3 setup.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
